name: Build and Upload Docker Image to JFrog

on:
  push:
    branches:
      - demo  # Trigger on push to the demo branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Docker Buildx for cross-platform builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to JFrog Artifactory Docker repository
    - name: Log in to JFrog Artifactory Docker repository
      run: echo ${{ secrets.JFROG_PASS }} | docker login talha001.jfrog.io -u ${{ secrets.JFROG_USERNAME }} --password-stdin

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t hello-world:latest .

    # Tag the Docker image with the Artifactory repository
    - name: Tag Docker image
      run: |
        docker tag demo-docker:latest talha001.jfrog.io/demo-docker/hello-world:latest

    # Push the Docker image to JFrog Artifactory
    - name: Push Docker image to JFrog Artifactory
      run: |
        docker push talha001.jfrog.io/demo-docker/demo-docker:latest
